Test insert
Hovspian/keystones pull request #1
Opened 2019-02-18 05:58 UTC by Hammerlord

- A separate insert keystone functionality from bot command
- Test cases for insert keystone
- Call str.lower() on dungeon names so that capitalization can be valid when retrieving the dungeon id

2019-02-18 20:01 UTC, Hovspian requested changes
The things related to saying the incorrect user input could be discussed since I think there are multiple good solutions

2019-02-18 20:01 UTC, Hovspian commented on keystones/tests/mocks.py
> +        self.author = DiscordUser()
I think it makes more sense to have the author as a parameter. Gives us more flexibility

2019-02-18 20:01 UTC, Hovspian commented on keystones/tests/mocks.py
> +    def __init__(self):
We should be able to pass in our own id and name since we will likely need multiple users. Can keep `1` and `Discord User` as defaults though

2019-02-18 20:01 UTC, Hovspian commented on keystones/core/command_validation.py
> +        return (f"I'm sorry, I didn't understand the dungeon `{dungeon}`. "
I'm not a fan of including the dungeon name here because of potential mention trolling by having backticks and a mention in the dungeon name

2019-02-18 20:01 UTC, Hovspian commented on keystones/core/command_validation.py
> +        return f"`{level}` isn't a valid dungeon level; please input a number."
Same as above

2019-02-18 20:01 UTC, Hovspian commented on keystones/core/command_validation.py
> +    character, *dungeon, level = args
I think we should also have some restrictions on character names. I definitely want to prevent having an @ in there because of mentions. Probably also backticks since that'll mess with our string formatting. Not sure if there's anything else.

This doesn't have to be done in this pr, since we're going to have to make some changes to match more closely with the current command version that we have.

2019-02-18 20:01 UTC, Hovspian commented on keystones/tests/tests.py
> +class KeystonesTests(unittest.TestCase):
I'd like the file and class to be renamed to be more specific (this one should probably just support `command_validation.py`) so that we can test each module individually.

2019-02-18 20:09 UTC, Hammerlord commented on keystones/core/command_validation.py
> +        return (f"I'm sorry, I didn't understand the dungeon `{dungeon}`. "
We can possibly scrub undesirable characters from inputs

2019-02-18 20:16 UTC, Hammerlord commented on keystones/tests/mocks.py
> +    def __init__(self):
There were a few ways we can customize these:
1) An autoincrement on the ID whenever we create one of these objects (so it just calls a ++int when we make one)
2) Just pass in or overwrite the properties on the instance
3) Use the Builder pattern to construct the mock objects, which start with defaults that can be selectively changed with method calls, eg.

class UserBuilder:
    def __init__(self):
        self.id = 1
        self.name = "Discord User"
        
    def with_name(self, name: str):
        self.name = name
        return self
    
    def build(self):
        return DiscordUser(self.id, self.name)

Although this feels kind of overengineered for a small object like the current fake DiscordUser.

2019-02-18 20:19 UTC, Hammerlord commented on keystones/core/command_validation.py
> +        return (f"I'm sorry, I didn't understand the dungeon `{dungeon}`. "
Other than that, I think showing the wrong input is useful so non-trolls can see where they went wrong, but yeah

2019-02-18 20:31 UTC, Hammerlord commented on keystones/tests/tests.py
> +class KeystonesTests(unittest.TestCase):
I think `command_validation` should probably be renamed if all it will contain is the insert keystone function. I was thinking it would hold more "command validations" since it's small at the moment, then we can decide to break it up later.

2019-02-18 22:28 UTC, Hovspian commented on keystones/tests/mocks.py
> +    def __init__(self):
I like the second option, like you did in the new commit. If we're doing a test with a lot of fake DiscordUsers the first would be a little more convenient, but the second is nice since we get more control over the objects and we'd probably be creating them in a loop where we'll be able to easily make distinct arguments for each iteration

2019-02-18 22:30 UTC, Hovspian commented on keystones/core/command_validation.py
> +        return (f"I'm sorry, I didn't understand the dungeon `{dungeon}`. "
Agreed. I wonder if there's actually a way to send a string as plaintext to the channel? Might not be 100% what we want, but could be worth looking into

2019-02-18 22:36 UTC, Hovspian commented on keystones/tests/mocks.py
> +    def __init__(self, content: str, author=DiscordUser()):
You actually want to use `None` as the default value for author and inside the function assign it to a value if it's still `None`. [It's not good to use a mutable as the default value](https://stackoverflow.com/questions/32939159/create-object-with-attributes-that-have-default-values-python). iirc it'll reuse the same DiscordUser here for every DiscordMessage that's made without an author

2019-02-18 22:39 UTC, Hovspian commented on keystones/tests/tests.py
> +class KeystonesTests(unittest.TestCase):
I think that after we merge this pr we could move all the existing commands over to `command_validation`, or use separate validations like you mentioned. Since we only have a few commands right now I think it would make sense keeping them together, but if we add a lot more we can split them up.

2019-02-18 22:56 UTC, Hammerlord commented on keystones/tests/mocks.py
> +    def __init__(self, content: str, author=DiscordUser()):
Oh lol, I was under the impression it would create a new `DiscordUser` every time... apparently not. I just assumed.

2019-02-19 01:17 UTC, Hovspian commented on keystones/tests/mocks.py
> +    def __init__(self, content: str, author=DiscordUser()):
Ya that was really surprising when I learned it too

2019-02-19 01:35 UTC, Hovspian commented on keystones/tests/mocks.py
> +    def __init__(self, content: str, author: DiscordUser or None):
```suggestion
    def __init__(self, content: str, author=None: DiscordUser):
```
This way would work better because then you don't actually have to pass None when creating a new object

2019-02-19 01:43 UTC, Hammerlord commented on keystones/tests/mocks.py
> +    def __init__(self, content: str, author: DiscordUser or None):
Oh yeah lol

2019-02-19 22:01 UTC, Hovspian approved these changes

2019-03-06 01:48 UTC, merged